global_costmap:
  update_frequency: 1
  publish_frequency: 1
  transform_tolerance: 5
  width: 5
  height: 5
  origin_x: -2.5
  origin_y: -2.5
  static_map: false
  rolling_window: true
  inflation_radius: 0.7
  resolution: 0.01
